Repository Aharoni-Lab/mio, pull requests merged in 2024-11, with the labels that each got.

#50 switch to PDM, rm nox
  .gitignore
  .readthedocs.yml
  docs/guide/installation.md
  docs/meta/contributing.md
  noxfile.py
  pdm.lock
  poetry.lock
  pyproject.toml
Labels: devops

#53 [ci] Add readthedocs preview links to PRs
  .github/workflows/docs-preview.yml
Labels: documentation, devops

#48 Over The Air device config feature
  docs/conf.py
  docs/device/update_controller.md
  docs/index.md
  miniscope_io/cli/main.py
  miniscope_io/cli/update.py
  miniscope_io/device_update.py
  miniscope_io/models/devupdate.py
  miniscope_io/plots/headers.py
  tests/test_device_update.py
  tests/test_models/test_model_devupdate.py
Labels: enhancement
